package tput

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func generateServerHandler(builder golang.ModuleBuilder, wrapped_service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package:   pkg,
		Service:   wrapped_service,
		Iface:     wrapped_service,
		Name:      wrapped_service.BaseName + "_TputHandler",
		IfaceName: wrapped_service.Name,
		Imports:   gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "time", "fmt", "github.com/vaastav/iridescent_rt/autotune")

	slog.Info(fmt.Sprintf("Generating %v/%v", server.Package.PackageName, wrapped_service.Name))
	outputFile := filepath.Join(server.Package.Path, wrapped_service.Name+".go")
	return gogen.ExecuteTemplateToFile("Tput", serverTemplate, server, outputFile)
}

type serverArgs struct {
	Package   golang.PackageInfo
	Service   *gocode.ServiceInterface
	Iface     *gocode.ServiceInterface
	Name      string
	IfaceName string
	Imports   *gogen.Imports
}

var serverTemplate = `// Blueprint: Auto-generated by Throughput Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.IfaceName}} interface {
	{{range $_, $f := .Iface.Methods -}}
	{{Signature $f}}
	{{end}}
}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	Counter int64
	ExpStarted bool
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Service = service
	handler.Counter = 0
	handler.ExpStarted = false
	autotune.GetRuntime().RegisterMeasurementFn(handler.MeasureTput)
	autotune.GetRuntime().RegisterObjFn(handler.Objective)
	return handler, nil
}

func (handler *{{.Name}}) MeasureTput() autotune.Stats {
	cntr := handler.Counter
	stats := autotune.Stats{Values: make(map[string]uint64)}
	stats.Values["tput"] = cntr
	handler.Counter = 0
	return stats
}

func (handler * {{.Name}}) Objective(s Stats) uint64 {
	return s.Values["tput"]
}

func (handler * {{.Name}}) IncrCounter(ctx context.Context) {
	if !handler.ExpStarted {
		autotune.GetRuntime().StartExploration(ctx)
		handler.ExpStarted = true
	}
	handler.Counter += 1
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetTypes $f "error"}}) {
	handler.IncrCounter(ctx)
	return handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
}
{{end}}
`
