import csv
from collections import defaultdict
import sys

def generate_countries_go(csv_file):
    outfile = "countries.go"

    continents = defaultdict(list)

    with open(csv_file, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            country = row["Three_Letter_Country_Code"].strip()
            if country == "":
                country = row["Two_Letter_Country_Code"]
            continent = row["Continent_Code"].strip()
            continents[continent].append(country)

        # Generate go_maps
        go_output = []
        for continent, countries in sorted(continents.items()):
            var_name = f"{continent}Countries"
            entries = "\n".join(
                f'\t"{c}": ' + "{}," for c in sorted(countries)
            )

            go_map = f"var {var_name} = map[string]struct" + "{}{" + f"\n{entries}\n" + "}"
            go_output.append(go_map)
        
        with open(outfile, 'w+') as outf:
            outf.write("//Auto-generated by countries.py\npackage workflow\n" + '\n\n'.join(go_output))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python countries.py <country_list.csv>")
        sys.exit(1)

    csv_path = sys.argv[1]
    generate_countries_go(csv_path)