package latency

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func generateServerHandler(builder golang.ModuleBuilder, wrapped_service *gocode.ServiceInterface, outputPackage string, percentile float64) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package:    pkg,
		Service:    wrapped_service,
		Iface:      wrapped_service,
		Name:       wrapped_service.BaseName + "_PercentileLatencyHandler",
		IfaceName:  wrapped_service.Name,
		Imports:    gogen.NewImports(pkg.Name),
		Percentile: percentile,
	}

	server.Imports.AddPackages("context", "time", "github.com/vaastav/raglan/iridescent_rt/autotune", "github.com/caio/go-tdigest/v5", "math", "sync")

	slog.Info(fmt.Sprintf("Generating %v/%v", server.Package.PackageName, server.Name))
	outputFile := filepath.Join(server.Package.Path, server.Name+".go")
	return gogen.ExecuteTemplateToFile("PercentileLatency", serverTemplate, server, outputFile)
}

type serverArgs struct {
	Package    golang.PackageInfo
	Service    *gocode.ServiceInterface
	Iface      *gocode.ServiceInterface
	Name       string
	IfaceName  string
	Imports    *gogen.Imports
	Percentile float64
}

var serverTemplate = `// Raglan: Auto-generated by Latency Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	td *tdigest.TDigest
	mu sync.Mutex
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Service = service
	handler.td, _ = tdigest.New()
	autotune.GetRuntime().RegisterMeasurementFn(handler.MeasureLat)
	autotune.GetRuntime().RegisterObjFn(handler.Objective)
	return handler, nil
}

func (handler *{{.Name}}) MeasureLat() autotune.Stats {
	handler.mu.Lock()
	defer handler.mu.Unlock()
	lat := uint64(handler.td.Quantile({{.Percentile}}))
	stats := autotune.Stats{Values: make(map[string]uint64)}
	stats.Values["per_lat"] = math.MaxUint64 - lat
	handler.td.Reset()
	return stats
}

func (handler *{{.Name}}) Objective(s autotune.Stats) uint64 {
	return s.Values["per_lat"]
}

func (handler *{{.Name}}) AddSample(d time.Duration) {
	handler.mu.Lock()
	defer handler.mu.Unlock()
	handler.td.Add(float64(d.Nanoseconds()))
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	start := time.Now()
	{{RetVars $f "err"}} = handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
	end := time.Now()
	elapsed := end.Sub(start)
	handler.AddSample(elapsed)
	return
}
{{end}}
`
