package latency

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func generateAvgServerHandler(builder golang.ModuleBuilder, wrapped_service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package:   pkg,
		Service:   wrapped_service,
		Iface:     wrapped_service,
		Name:      wrapped_service.BaseName + "_AverageLatencyHandler",
		IfaceName: wrapped_service.Name,
		Imports:   gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "time", "github.com/vaastav/raglan/iridescent_rt/autotune", "math")

	slog.Info(fmt.Sprintf("Generating %v/%v", server.Package.PackageName, server.Name))
	outputFile := filepath.Join(server.Package.Path, server.Name+".go")
	return gogen.ExecuteTemplateToFile("AverageLatency", avgServerTemplate, server, outputFile)
}

var avgServerTemplate = `// Raglan: Auto-generated by Latency Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	total time.Duration
	count uint64
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Service = service
	autotune.GetRuntime().RegisterMeasurementFn(handler.MeasureLat)
	autotune.GetRuntime().RegisterObjFn(handler.Objective)
	return handler, nil
}

func (handler *{{.Name}}) MeasureLat() autotune.Stats {
	var lat uint64
	if handler.count == 0 {
		lat = math.MaxUint64
	} else {
		avg := handler.total / time.Duration(handler.count)
		lat = uint64(avg.Nanoseconds())
	}
	stats := autotune.Stats{Values: make(map[string]uint64)}
	stats.Values["avg_lat"] = math.MaxUint64 - lat
	handler.total = 0
	handler.count = 0
	return stats
}

func (handler *{{.Name}}) Objective(s autotune.Stats) uint64 {
	return s.Values["avg_lat"]
}

func (handler *{{.Name}}) AddSample(d time.Duration) {
	handler.total += d
	handler.count++
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	start := time.Now()
	{{RetVars $f "err"}} = handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
	end := time.Now()
	elapsed := end.Sub(start)
	handler.AddSample(elapsed)
	return
}
{{end}}
`
